<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <XamlDebuggingInformation>True</XamlDebuggingInformation>
    <PlatformTarget>x64</PlatformTarget>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Platforms>x64</Platforms>
    <Configurations>DebugEditor;ReleaseEditor</Configurations>
    <BaseOutputPath>..\</BaseOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='DebugEditor|x64'">
    <Optimize>True</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Resources\ContentBrowser\openImportConfigs.png" />
  </ItemGroup>
	
  <ItemGroup>
    <Resource Include="Resources\ContentBrowser\listView.png" />
    <Resource Include="Resources\ContentBrowser\tileView.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\ContentBrowser\largeFolder.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\ContentBrowser\folder.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\PrimitiveMeshView\chess.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\TextureEditor\ChannelShader.cso" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\PrimitiveMeshView\vilekuna.png" />
    <Resource Include="Resources\TextureEditor\chess.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Themes\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="envdte" Version="17.14.40260" />
    <PackageReference Include="envdte80" Version="17.14.40260" />
  </ItemGroup>

</Project>
